# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{genability}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matthew Solt"]
  s.date = %q{2011-07-01}
  s.description = %q{Ruby client for the Genability power pricing and related APIs - learn more at https://developer.genability.com}
  s.email = %q{mattsolt@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.md",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".yardopts",
    "Gemfile",
    "HISTORY.md",
    "LICENSE.md",
    "README.md",
    "Rakefile",
    "VERSION",
    "genability.gemspec",
    "lib/faraday/response/raise_http_4xx.rb",
    "lib/faraday/response/raise_http_5xx.rb",
    "lib/genability.rb",
    "lib/genability/api.rb",
    "lib/genability/client.rb",
    "lib/genability/client/helpers.rb",
    "lib/genability/client/load_serving_entity.rb",
    "lib/genability/client/price.rb",
    "lib/genability/client/season.rb",
    "lib/genability/client/tariff.rb",
    "lib/genability/client/territory.rb",
    "lib/genability/client/time_of_use.rb",
    "lib/genability/client/zip_code.rb",
    "lib/genability/configuration.rb",
    "lib/genability/connection.rb",
    "lib/genability/error.rb",
    "lib/genability/request.rb",
    "spec/cassettes/load_serving_entities.yml",
    "spec/cassettes/load_serving_entity.yml",
    "spec/cassettes/prices.yml",
    "spec/client/load_serving_entity_spec.rb",
    "spec/client/price_spec.rb",
    "spec/configuration.yml.sample",
    "spec/faraday/response_spec.rb",
    "spec/genability_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/activefx/genability}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby client for the Genability API}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<faraday>, ["~> 0.6"])
      s.add_runtime_dependency(%q<faraday_middleware>, ["~> 0.6"])
      s.add_runtime_dependency(%q<hashie>, ["~> 1.0.0"])
      s.add_runtime_dependency(%q<multi_json>, ["~> 1.0.0"])
      s.add_runtime_dependency(%q<chronic>, ["~> 0.4.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.7.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.4"])
      s.add_development_dependency(%q<vcr>, ["~> 1.10.0"])
      s.add_development_dependency(%q<webmock>, ["~> 1.6.0"])
    else
      s.add_dependency(%q<faraday>, ["~> 0.6"])
      s.add_dependency(%q<faraday_middleware>, ["~> 0.6"])
      s.add_dependency(%q<hashie>, ["~> 1.0.0"])
      s.add_dependency(%q<multi_json>, ["~> 1.0.0"])
      s.add_dependency(%q<chronic>, ["~> 0.4.0"])
      s.add_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_dependency(%q<yard>, ["~> 0.7.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_dependency(%q<simplecov>, ["~> 0.4"])
      s.add_dependency(%q<vcr>, ["~> 1.10.0"])
      s.add_dependency(%q<webmock>, ["~> 1.6.0"])
    end
  else
    s.add_dependency(%q<faraday>, ["~> 0.6"])
    s.add_dependency(%q<faraday_middleware>, ["~> 0.6"])
    s.add_dependency(%q<hashie>, ["~> 1.0.0"])
    s.add_dependency(%q<multi_json>, ["~> 1.0.0"])
    s.add_dependency(%q<chronic>, ["~> 0.4.0"])
    s.add_dependency(%q<rspec>, ["~> 2.6.0"])
    s.add_dependency(%q<yard>, ["~> 0.7.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
    s.add_dependency(%q<simplecov>, ["~> 0.4"])
    s.add_dependency(%q<vcr>, ["~> 1.10.0"])
    s.add_dependency(%q<webmock>, ["~> 1.6.0"])
  end
end

